### ISSUE TITLE
 Non-fatal error when unusual message are tracked in chat

### ISSUE THREAD

**Issue by ShaneTRS** [KrLite/Ive-Spoken#1]
Relevant line: https://github.com/KrLite/Ive-Spoken/blob/9fcd0a9922e6fb7476c48422e61f720705c0d3d5/src/main/java/net/krlite/ive_spoken/mixin/ChatTracker.java#L20

I fixed the bug locally with the following change:
```java
	if (args.length == 2 && args[1] instanceof MutableText) {
```

Although non-fatal, it disrupted the chat message appearing in chat. Instead replacing it with a shorthand form of the error.

**Comment by KrLite** [comment]
Good solve and thanks for contributing! Changes will be made soon in the next version.

**Comment by KrLite** [comment]
Fixed in [`v1.0.1`.](https://modrinth.com/mod/ive-spoken/version/1.20-v1.0.1)
