### ISSUE TITLE
[BUG] Not Working on Servers

### ISSUE THREAD

**Issue by Panetina** [KrLite/Ive-Spoken#3]
I installed this mod on my client and it doesn't work, should I install it on the server also?

**Comment by Panetina** [comment]
I installed it on the server too as well as on both clients. There is no text above the other player's head when he send a message.

**Comment by Panetina** [comment]
Game version 1.20.4 and Fabric 0.15.7

**Comment by KrLite** [comment]
It should work with your client only, there must be something wrong. What mod version are you using and what other mods have you installed?

**Comment by nco2k** [comment]
i have the same issue. even in single player nothing happens. i have a ton of mods installed, so its difficult to figure out if its an incompatibly with another mod. every mod that messes with the chat, i have already disabled. still no luck.

**Comment by KrLite** [comment]
@Panetina @nco2k Could you please test again with the following jar file?

https://github.com/KrLite/Mod.Ive-Spoken/releases/download/2.0.3-alpha.1-mc1.20/ivespoken-1.20-2.0.3-alpha.1.jar

I have tested it locally in my development environment with LAN worlds. It worked, and hence I cannot determine what the real problem is. **Please post the *game log file* (probably under `.minecraft/logs/latest.log`) after tested if possible, thanks!**

**Comment by Panetina** [comment]
> @Panetina @nco2k Could you please test again with the following jar file?
> 
> https://github.com/KrLite/Mod.Ive-Spoken/releases/download/2.0.3-alpha.1-mc1.20/ivespoken-1.20-2.0.3-alpha.1.jar
> 
> I have tested it locally in my development environment with LAN worlds. It worked, and hence I cannot determine what the real problem is. **Please post the _game log file_ (probably under `.minecraft/logs/latest.log`) after tested if possible, thanks!**

[latest.log](https://github.com/KrLite/Mod.Ive-Spoken/files/14592828/latest.log)
Still the same, nothing appears.

**Comment by KrLite** [comment]
> > @Panetina @nco2k Could you please test again with the following jar file?
> 
> > 
> 
> > https://github.com/KrLite/Mod.Ive-Spoken/releases/download/2.0.3-alpha.1-mc1.20/ivespoken-1.20-2.0.3-alpha.1.jar
> 
> > 
> 
> > I have tested it locally in my development environment with LAN worlds. It worked, and hence I cannot determine what the real problem is. **Please post the _game log file_ (probably under `.minecraft/logs/latest.log`) after tested if possible, thanks!**
> 
> 
> 
> [latest.log](https://github.com/KrLite/Mod.Ive-Spoken/files/14592828/latest.log)
> 
> Still the same, nothing appears.
> 
> 

It turns out that the mod had successfully received player chats. The bug is in rendering. 🤔
![image](https://github.com/KrLite/Mod.Ive-Spoken/assets/68179735/69d69117-0e45-4c33-a69d-3778b5c7f466)

**Comment by KrLite** [comment]
> > @Panetina @nco2k Could you please test again with the following jar file?
> 
> > 
> 
> > https://github.com/KrLite/Mod.Ive-Spoken/releases/download/2.0.3-alpha.1-mc1.20/ivespoken-1.20-2.0.3-alpha.1.jar
> 
> > 
> 
> > I have tested it locally in my development environment with LAN worlds. It worked, and hence I cannot determine what the real problem is. **Please post the _game log file_ (probably under `.minecraft/logs/latest.log`) after tested if possible, thanks!**
> 
> 
> 
> [latest.log](https://github.com/KrLite/Mod.Ive-Spoken/files/14592828/latest.log)
> 
> Still the same, nothing appears.
> 
> 

The log indicates that the mod had received player messages, so the bug is in rendering. That's weird. 🤔
![image](https://github.com/KrLite/Mod.Ive-Spoken/assets/68179735/bdc2e0f7-e5c8-4966-8e5d-2ec12f74dde7)

**Comment by Panetina** [comment]
Could shaderpacks be an issue?

**Comment by KrLite** [comment]
> Could shaderpacks be an issue?

I can't tell, but probably not. If you are available, could you please test it in a new Minecraft instance with only **I've Spoken** (and its dependencies) installed and see if it works?

I'm suspecting Minecraft `1.20.4` for some code inconsistencies with `1.20`, which the mod is developed on.

**Comment by Panetina** [comment]
On a clean server/client, it worked. So I guess it may be due to some mods that also affect/add stuff to the player:
https://modrinth.com/mod/mob-plaques
https://modrinth.com/mod/not-enough-animations/version/1.6.3-1.19.4
These are the only ones I have on the client that add something to the player.

Game log
[latest.log](https://github.com/KrLite/Mod.Ive-Spoken/files/14601548/latest.log)
---
Server log
[latest.log](https://github.com/KrLite/Mod.Ive-Spoken/files/14601554/latest.log)

**Comment by Panetina** [comment]
Nvm, I put those together too and it worked.. Then maybe other mod from that modpack, unrelated directly to the player, is the problem

**Comment by KrLite** [comment]
> Nvm, I put those together too and it worked.. Then maybe other mod from that modpack, unrelated directly to the player, is the problem

Then it will be very hard to debug. It would be good of you to spare some time to figure out what mods are really affecting this mod. If not, I will check them out one by one this weekend.

In case you don't know, a fast way of debugging is disabling half of the mods each time and launch, and check if the bug still appears. If not, mark the disabled mods unsafe, and do it to them again and again.
