### ISSUE TITLE
[BUG/CRASH]: Crashes on entrypoint load [Fabric 1.20.1/0.16.0] 

### ISSUE THREAD

**Issue by pokesmells** [KrLite/Ive-Spoken#4]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### What Happened?

Crashed on start upo

### What Should Happen?

NOT CRASH :D

### Steps to Reproduce

Add mod, cloth config supposedly, and launch, crash game

### Crash Log

https://mclo.gs/2BjpOKM

**Comment by KrLite** [comment]
This is a bug of **[Night Auto Config.](https://github.com/KessokuTeaTime/Night-Auto-Config)** Fixed in [`2.2.1`](https://modrinth.com/mod/ive-spoken/version/2.2.1-fabric1.20).
