### ISSUE TITLE
[BUG] Installs OLD version of Cloth Config when installing I've Spoken [Fabric 0.16.0/1.20.1]

### ISSUE THREAD

**Issue by pokesmells** [KrLite/Ive-Spoken#5]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### What Happened?

Whenever I download "I've Spoken" On Curseforge, it downloads "Cloth API" Which is the old version of Cloth Config API, and it cannot be used on modern loaders, it is by nature not able to be used.

![image](https://github.com/user-attachments/assets/61e12d12-d000-46ab-bbf3-b3445a258264)

### What Should Happen?

It should just require "Cloth Config API (Fabric/Forge/NeoForge)" which is the new one

### Steps to Reproduce

Go to CF

Download "I've Spoken"

And get the wrong config API which causes a crash

### Crash Log

https://mclo.gs/soUVAf3

### Anything Else?

It may need it's dependencies fixed within the mod

**Comment by KrLite** [comment]
Thanks for reporting! It's not a big problem, just that I filled the wrong id of the dependency when publishing to CurseForge. Later I will modify them and it shall be all right, and no updates are needed. I'll notice you then.

**Comment by KrLite** [comment]
This issue is fixed. The problem comes from the mod **[Night Auto Config,](https://www.curseforge.com/minecraft/mc-mods/night-auto-config)** and I will fill the dependencies more carefully in the future.
